### ISSUE TITLE
Add ability to set scaleX and scaleY separately for viewport in flower

### ISSUE THREAD

**Issue by Vavius** [makotok/Hanappe#93]
Maybe, viewport handling should be redone in flower. 
Now it forces to use coordinate system where y = 0 at top. 

While that setting is OK for GUI-intensive apps, it's not very suitable for physics games, platformers, and such. 

Maybe we could find a solution? Problem seems pretty hard, since all widgets and probably other extensions are coordinate system dependent. Also, all texture coordinates should be flipped as well.

**Comment by makotok** [comment]
The default viewport options have been added.
